### PR TITLE
combined preparation for the 6.3.0 release and a regression resolution

### LINKED ISSUE #611: setuptools-scm 6.2.0 has no such extra feature 'toml
:wave: we just started seeing this in our docs build: https://readthedocs.org/projects/ddtrace/builds/14573515/

`/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/bin/python ./setup.py install --force`

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2739, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'toml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./setup.py", line 150, in <module>
    setup(
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2741, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'
```

haven't gotten a chance to dig in further - will update if I get the chance!

### LINKED ISSUE #612: AttributeError: 'Version' object has no attribute 'release' after upgrade to 6.2.0
Related to #605 and #607.

I was just running a CI job to create wheels and sdist for the vispy project and it just picked up setuptools_scm 6.2.0 (released 16 minutes ago) and fails during sdist building. I noticed #607 says that modern setuptools should use pip. What is the recommended way to build an sdist package if not `python setup.py sdist` to avoid this error?

```
 Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    'Framework :: IPython'
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/setuptools/dist.py", line 426, in __init__
    k: v for k, v in attrs.items()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/setuptools/dist.py", line 717, in finalize_options
    ep(self)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/setuptools/dist.py", line 724, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/runner/work/vispy/vispy/.eggs/setuptools_scm-6.2.0-py3.7.egg/setuptools_scm/integration.py", line 29, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/home/runner/work/vispy/vispy/.eggs/setuptools_scm-6.2.0-py3.7.egg/setuptools_scm/__init__.py", line 192, in _get_version
    template=config.write_to_template,
  File "/home/runner/work/vispy/vispy/.eggs/setuptools_scm-6.2.0-py3.7.egg/setuptools_scm/__init__.py", line 94, in dump_version
    version_fields = parsed_version.release
AttributeError: 'Version' object has no attribute 'release'
```

### LINKED ISSUE #615: v6.1.0 breaks setuptools_scm_git_archive — AttributeError: 'NoneType' object has no attribute 'version_cls'
HI,
I think a minor release should not break packages so I am creating a report here (I will also create one at `https://github.com/Changaco/setuptools_scm_git_archive/`).

Commit fbadf5b060cdd7ec1fb3d29d885868b7b756497c broke `setuptools_scm_git_archive`. Here is an example traceback:
```
/usr/local/lib/python3.9/site-packages/setuptools_scm/version.py:212: UserWarning: meta invoked without explicit configuration, will use defaults where required.
  warnings.warn(
Traceback (most recent call last):
  File "/pikepdf-2.16.1/setup.py", line 38, in <module>
    __version__ = get_version()
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 170, in get_version
    return _get_version(config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 174, in _get_version
    parsed_version = _do_parse(config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
    version = _call_entrypoint_fn(root, config, ep.load())
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 54, in _call_entrypoint_fn
    return fn(root)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm_git_archive/__init__.py", line 21, in parse
    return archival_to_version(data)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm_git_archive/__init__.py", line 15, in archival_to_version
    return meta(versions[0])
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/version.py", line 216, in meta
    parsed_version = _parse_tag(tag, preformatted, config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/version.py", line 195, in _parse_tag
    version_cls = config.version_cls or VERSION_CLASS
AttributeError: 'NoneType' object has no attribute 'version_cls'
```

This can be easily  reproduced with this Dockerfile:
```Dockerfile
FROM python:3.9
RUN wget -nv https://github.com/pikepdf/pikepdf/archive/v2.16.1.tar.gz
RUN tar xf v2.16.1.tar.gz
WORKDIR pikepdf-2.16.1

RUN pip3 install setuptools_scm_git_archive
# Bad 
RUN pip3 install git+https://github.com/pypa/setuptools_scm@fbadf5b060cdd7ec1fb3d29d885868b7b756497c

# The parent commit was still good
#RUN pip3 install git+https://github.com/pypa/setuptools_scm@b8451688b9cb295136c0154c7c59c25a9d88f844

RUN python setup.py --version
```

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this fixes the support for old setuptools while not starting to claim to support old setuptools

* fix #612: depend on packaging to ensure version parsing parts
* fix #611: correct the typo that hid away the toml extra and add it in ``setup.py`` as well
* fix #615: restore support for the git_archive plugin which doesn't pass over the config

### CODE REVIEW

File: src/setuptools_scm/integration.py [hunk 1]
```diff
@@ -9,6 +9,31 @@
 from .utils import trace
 
 
+def _break_on_old_setuptools(_version=setuptools.__version__):
+    if int(_version.split(".")[0]) < 45:
+        raise SystemExit(
+            f"""
+ERROR: setuptools=={_version} is used in combination with setuptools_scm>=6.x
+
+Your build configuration is incomplete and worked by accident!
```
Comment (FFY00) [inline src/setuptools_scm/integration.py]:
```suggestion
Your build configuration is incomplete and previously worked by accident!
```

File: src/setuptools_scm/integration.py [hunk 2]
```diff
@@ -9,6 +9,31 @@
...
+Please ensure setuptools>=45 and setuptools_scm>=6.2 are installed with current tools.
```
Comment (FFY00) [inline src/setuptools_scm/integration.py]: This sentence is confusing to me. I think you mean to say that we should use PEP 517 tooling, which provisions the environment by default, right? If so,

```suggestion
Please ensure setuptools>=45 and setuptools_scm>=6.2 are built with recent tooling.
```

Even then, I am no so sure this is sentence is clear. Perhaps it would be best to just remove it in favor of the last point of the list below?

File: src/setuptools_scm/integration.py [hunk 3]
```diff
@@ -9,6 +9,31 @@
...
+
+This happens as setuptools is unable to replace itself when a activated build dependeny
+requires a more recent setuptools version.
```
Comment (FFY00) [inline src/setuptools_scm/integration.py]:
```suggestion
requires a more recent setuptools version (it does not respect "setuptools>X" in setup_requires).
```

File: src/setuptools_scm/integration.py (hunk 2 above)
Comment (RonnyPfannschmidt) [reply src/setuptools_scm/integration.py]:
```suggestion
```

File: src/setuptools_scm/integration.py [hunk 4]
```diff
@@ -9,6 +9,30 @@
 from .utils import trace
 
 
+def _break_on_old_setuptools(_version=setuptools.__version__):
+    if int(_version.split(".")[0]) < 45:
+        raise SystemExit(
+            f"""
+ERROR: setuptools=={_version} is used in combination with setuptools_scm>=6.x
```
Comment (wbolster) [inline src/setuptools_scm/integration.py:19]: this should probably read 7.x?

File: testing/Dockerfile.busted-buster [hunk 5]
```diff
@@ -0,0 +1,3 @@
+FROM debian:buster
+RUN apt-get update -q && apt-get install -yq python3-pip python3-setuptools
+RUN echo -n "[easy_install]\nallow_hosts=localhost\nfind_links=/dist" > /root/.pydistutils.cfg
```
Comment (wbolster) [inline testing/Dockerfile.busted-buster]: this is incorrect as it prints a single line:

```
$ echo -n "[easy_install]\nallow_hosts=localhost\nfind_links=/dist"
[easy_install]\nallow_hosts=localhost\nfind_links=/dist
```

`echo -e` could work, or better yet: use `printf` to move _all_ the escapes into the string (instead of having the intermediate newlines added by the escapes, and the final newline implicitly by `echo`)

```suggestion
RUN printf "[easy_install]\nallow_hosts=localhost\nfind_links=/dist\n" > /root/.pydistutils.cfg
```

**Review by FFY00 — APPROVED** [review]
:rocket:

File: .github/workflows/python-tests.yml [hunk 6]
```diff
@@ -49,6 +49,17 @@ jobs:
         if: matrix.os == 'ubuntu-latest'
       - run: pytest
 
+  test_legacy_setuptools:
+    runs-on: ubuntu-lates
```
Comment (henryiii) [inline .github/workflows/python-tests.yml]:
```suggestion
    runs-on: ubuntu-latest
```

File: CHANGELOG.rst [hunk 7]
```diff
@@ -1,3 +1,27 @@
...
+   This unfortunately has to happen as the legacy ``setup_requires`` mechanism
+   incorrectly configures the setuptools working-set when a more recent setuptools
+   version than available is required.
+
+   As all releases of setuptools are affected as the historic mechanism
+   for ensuring a working setuptools setup was shipping a ``ez_setup`` file
+   next to ``setup.py``, which would install the required version of setuptools.
+
+   This mechanism has long since been deprecated and removed
+   as most people haven't been using it
```
Comment (henryiii) [inline CHANGELOG.rst:17]:
```suggestion
   as most people haven't been using it.
```

File: setup.cfg [hunk 8]
```diff
@@ -27,8 +27,8 @@ classifiers =
 [options]
 packages = find:
 install_requires =
-    setuptools>=45
-    tomli>=1.0
+    packaging>=20.0
+    setuptools
```
Comment (henryiii) [inline setup.cfg:31]: Do you know what the actual minimum is? 31? Might be nice here even just for documentation?

File: CHANGELOG.rst (hunk 7 above)
Comment (henryiii) [reply CHANGELOG.rst:17]: Also, on this block, mentioning what version is too old and going to produce the warning might be helpful. This starts by saying "warns on legacy" but then says "all releases are affected", it's really unclear, I think. Maybe I could suggest a new version?


```rst
This release explicitly warns on unsupported setuptools. When using the legacy 
``setup_requires`` mechanism, you cannot request a newer setuptools than the
one currently running (this was the reason PEP 517 and PEP 518 were written).
```

File: src/setuptools_scm/__init__.py [hunk 9]
```diff
@@ -52,15 +48,16 @@ def _call_entrypoint_fn(root, config, fn):
         return fn(root, config=config)
     else:
         warnings.warn(
-            "parse functions are required to provide a named argument"
-            " 'config' in the future.",
-            category=PendingDeprecationWarning,
+            f"parse function {fn.__module__}.{fn.__name__}"
+            " are required to provide a named argument"
+            " 'config', setuptools_scm>=8.0 will remove support.",
```
Comment (henryiii) [inline src/setuptools_scm/__init__.py:53]: Is this 8? Or is this going to be 7 now?

File: src/setuptools_scm/integration.py [hunk 10]
```diff
@@ -1,14 +1,48 @@
...
-from . import Configuration
+from .config import _read_dist_name_from_setup_cfg
+from .config import Configuration
 from .utils import do
 from .utils import iter_entry_points
 from .utils import trace
 
 
+def _warn_on_old_setuptools(_version=setuptools.__version__):
+    if int(_version.split(".")[0]) < 45:
```
Comment (henryiii) [inline src/setuptools_scm/integration.py:15]: Is this 31 or 42? Does this only get triggered on the pyproject.toml codepath? Should not be 45, at least, that's only required to build setuptool_scm itself, IIUC.

File: src/setuptools_scm/integration.py (hunk 4 above)
Comment (henryiii) [reply src/setuptools_scm/integration.py:19]: This is 6.2 or 6.3 now?

File: tox.ini [hunk 11]
```diff
@@ -3,7 +3,9 @@ envlist=py{36,37,38,39,310}-test,flake8,check_readme,check-dist,py{37}-selfcheck
 
 [pytest]
 testpaths=testing
-filterwarnings=error
+filterwarnings=
+    error
+    ignore:.*tool\.setuptools_scm.*
```
Comment (henryiii) [inline tox.ini:8]: Wouldn't it be better to use `with pytest.warns`? Don't you want to ensure the warning are showing up, and be alerted if they are not?

**Review by henryiii — COMMENTED** [review]
If you want to make an RC release, I can try it out on a couple projects (though I'm going to be be heavily biased toward pyproject.toml projects, don't think I have any legacy ones).

File: tox.ini (hunk 11 above)
Comment (RonnyPfannschmidt) [reply tox.ini:8]: only in the tests for them

File: src/setuptools_scm/integration.py (hunk 10 above)
Comment (RonnyPfannschmidt) [reply src/setuptools_scm/integration.py:15]: setuptools 45 is the target intended minimal version (i dont plan to loosen that up)

File: src/setuptools_scm/__init__.py (hunk 9 above)
Comment (RonnyPfannschmidt) [reply src/setuptools_scm/__init__.py:53]: its going to be removed in 8.x

File: setup.cfg (hunk 8 above)
Comment (RonnyPfannschmidt) [reply setup.cfg:31]: the tested minimums are part of the long error now

File: CHANGELOG.rst (hunk 7 above)
Comment (RonnyPfannschmidt) [reply CHANGELOG.rst:17]: all setuptools releases are affected by the issue, even those that dont trigger legacy problems

Comment (henryiii) [reply CHANGELOG.rst:17]: Yes, but this is a general issue that has nothing to do with setuptools_scm, it's just easy to hit with it. The current message makes it sound like it's a major issue that most users will hit, while in actuality, now that 31+ is supported instead of 45+, it's only going to pop up in very old systems - which you should be unlikely to hit with Python 3.6+ (though possible). My suggested replacement makes it sound a little less drastic and pushes people gently toward PEP 517/518, which avoids triggering legacy behavior.

File: setup.cfg (hunk 8 above)
Comment (henryiii) [reply setup.cfg:31]: Yes, but this is a good place to easily see the minimums, rather than after the error has been triggered. And it's not as "public" as the minimums listed in the docs, which could be 45+.
