### ISSUE TITLE
Regression after #800

### ISSUE THREAD

**Issue by KOLANICH** [pypa/setuptools-scm#838]
After #800 got landed `setuptools_scm` has started breaking https://github.com/ofek/hatch-vcs (https://github.com/pypa/hatch/issues/795) .

78e7d6bb470e3c0ae5fd744e572f6e6085401a33 - can build itself, breaks hatch_vcs
bf0e8134e6b2101031acc3b3bb7b9bb4d2e6dd1b - cannot build itself, version.py:15, ImportError: cannot import name '_call_version_scheme' from partially initialized module 'setuptools_scm._entrypoints'
45ad9c82ec68096ff76a3a195598d98a7e426423 - cannot build itself, version.py:15, ImportError: cannot import name '_call_version_scheme' from partially initialized module 'setuptools_scm._entrypoints'
8e4e22fa18fc274f1839965bd7855716d72b8363 - cannot build itself, version.py:15, ImportError: cannot import name '_call_version_scheme' from partially initialized module 'setuptools_scm._entrypoints'
4208223520c72bad5ab47f31dbc4ab166874c27b - cannot build itself, version.py:15, ImportError: cannot import name '_call_version_scheme' from partially initialized module 'setuptools_scm._entrypoints'
fd04e244cdebae5398e37aa7c70bace604012673 - cannot build itself, version.py:15, ImportError: cannot import name '_call_version_scheme' from partially initialized module 'setuptools_scm._entrypoints'
91061f90e292e7aacc71bc8045b38ee1261f4c07 - cannot build itself, version.py:18 ImportError: cannot import name '_get_ep' from partially initialized module 'setuptools_scm._entrypoints'
770d5dd8d9366679865a8d25e71a381b527833d6 - works fine

**Comment by RonnyPfannschmidt** [comment]
should e resolved on master now

**Comment by KOLANICH** [comment]
No, it's not resolved. I test on https://github.com/python/black and use the command `python3 -m build -nwx`.

**Comment by RonnyPfannschmidt** [comment]
ok, now i have a local reproducer and found 2 bugs that need extra tests, will implement tommorow

**Comment by RonnyPfannschmidt** [comment]
@ofek this comes down to hatch-vcs passing in a empty string, i'll make this something that triggers a deprecation warning and will fail in a year or so

**Comment by KOLANICH** [comment]
I confirm, that now it works. Thanks for investigating and fixing it.

**Comment by RonnyPfannschmidt** [comment]
@KOLANICH btw, it is uncommon to have unreleased versions in use, im curious as to what types of pipeline need/want that (setuptools_scm is currently are not set up for true CI , so thee is a certain risk with that)

**Comment by KOLANICH** [comment]
I just prefer using bleeding edge versions of software to
1. get the latest fixes and features
2. get aware of the bugs affecting me before they are standardized as "features" compatibility to which is carefully conserved ("we don't hide problems" principle, and IMHO bugs should be fixed, not standardized)
3. reduce risk of compromise due to relying on the blob in the package registry that noone audits

Some rare breakages are not considered so bad, but instead are viewed as an opportunity to interfere before bugs are cast in stone as "features". Except of them, just installing the most of Python packages from git works pretty fine and I'm making a package manager as a replacement (in fact not quite a replacement, since it relies on some pip machinery and also `pip` is used to install the packages the ususal way) for `pip` with the main focus to be used in CI pipelines.
