### ISSUE TITLE
setuptools_scm 3.0.6: `version_from_scm()` fails under Python2

### ISSUE THREAD

**Issue by jeremytrimble** [pypa/setuptools-scm#297]
When I invoke `setuptools_scm.version_from_scm()` within my Python 2 program, I get a stacktrace:

```
Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/dist-packages/setuptools_scm/__init__.py", line 28, in version_from_scm
    return _version_from_entrypoint(root, "setuptools_scm.parse_scm")
  File "/usr/local/lib/python2.7/dist-packages/setuptools_scm/__init__.py", line 44, in _version_from_entrypoint
    for ep in iter_matching_entrypoints(config.absolute_root, entrypoint):
AttributeError: 'str' object has no attribute 'absolute_root'
```

This error occurs with version 3.0.6.  Everything worked fine under 2.1.0.

Appears to have been introduced in PR #276, looks similar to #281.

Python 2 is still intended to be supported, right?

Thanks for your work on `setuptools_scm`!  Sorry some of us are still stuck on Python 2 :-/

**Comment by jeremytrimble** [comment]
Same issue also exists in 3.0.2.

**Comment by RonnyPfannschmidt** [comment]
@jeremytrimble this is an unintended api cahnge, i will release a fix sometime later

can you point out how/where you use it?

**Comment by jeremytrimble** [comment]
@RonnyPfannschmidt: The code's in a private project, but it looks something like this:

```
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))                                                                                                                                                                                  
version = setuptools_scm.version_from_scm( project_root ) 
```
This appears in a file that's one directory down in my project's tree, so I'm basically just passing the full path to the root of my project (e.g. the directory that contains the `.git` directory).

Thanks for your help!

**Comment by jeremytrimble** [comment]
Thanks for addressing, @RonnyPfannschmidt.  I'll update my callers.
